# Generated by Django 5.0.6 on 2024-05-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Film',
            new_name='Movie',
        ),
    ]
