# Generated by Django 5.0.6 on 2024-05-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_year_alter_movie_tytul'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='Images'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=4),
            preserve_default=False,
        ),
    ]
