# Generated by Django 5.0.6 on 2024-05-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_description_movie_pictures_movie_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tytul',
            new_name='title',
        ),
    ]
