# Generated by Django 5.0.6 on 2024-05-30 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_tytul_movie_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.PositiveSmallIntegerField(choices=[(6, 'Horror'), (5, 'Drama'), (4, 'Comedy'), (0, 'Familly'), (1, 'Anime'), (3, 'Fantasy'), (2, 'Sci-fi')], default=0)),
                ('age', models.PositiveSmallIntegerField(choices=[(0, '+13'), (0, '+7'), (0, '+18')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='spec_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.info'),
        ),
    ]
