# Generated by Django 5.0.6 on 2024-05-31 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_info_movie_spec_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='age',
            field=models.PositiveSmallIntegerField(choices=[(0, '+7'), (1, '+13'), (2, '+18')], default=0),
        ),
        migrations.AlterField(
            model_name='info',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Horror'), (4, 'Comedy'), (0, 'Familly'), (3, 'Fantasy'), (2, 'Sci-fi'), (1, 'Anime'), (5, 'Drama')], default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
